repos:
  # Built-in hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # frozen: v6.0.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ["--maxkb=1000"]
      - id: mixed-line-ending
      - id: check-case-conflict

  # Ruff - Fast Python linter (replaces flake8, isort, and more)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: f298305809c552671cc47e0fec0ba43e96c146a2 # frozen: v0.13.2
    hooks:
      # Run the linter
      - id: ruff
        args: [--fix]
      # Run the formatter
      - id: ruff-format

  # mypy - Static type checker
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 9f70dc58c23dfcca1b97af99eaeee3140a807c7e # frozen: v1.18.2
    hooks:
      - id: mypy
        additional_dependencies: [pandas-stubs, types-requests]
        args: [--ignore-missing-imports]

  # Bandit - Security linter
  - repo: https://github.com/PyCQA/bandit
    rev: 2d0b675b04c80ae42277e10500db06a0a37bae17 # frozen: 1.8.6
    hooks:
      - id: bandit
        additional_dependencies: [pbr]
        args: ["-r"]
        files: \.py$
        exclude: ^tests/

  # Check Python docstrings
  - repo: https://github.com/pycqa/pydocstyle
    rev: 07f6707e2c5612960347f7c00125620457f490a7 # frozen: 6.3.0
    hooks:
      - id: pydocstyle
        args: [--convention=google]
        exclude: ^(tests/|migrations/)

  # YAML, JSON, and other file formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: f12edd9c7be1c20cfa42420fd0e6df71e42b51ea # frozen: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types_or: [yaml, json, markdown]
        exclude: ^(\.vscode/|\.idea/)
